service: messenger-bot
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1

functions:
  message:
    handler: index.handler
    memorySize: 1600
    timeout: 60
    events:
      - schedule: cron(0 * * * * *)
